pipeline:
  projectIdentifier: Labs
  orgIdentifier: Customer_Experience
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: Lab
            deployToAll: false
            infrastructureDefinitions:
              - identifier: labinfrastructure
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: testing
        identifier: testing
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: labk8sconnector
              namespace: gowri
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: podinfodockerconnectorpublish
                    image: nginx:latest
                    shell: Sh
                    command: |-
                      echo "hello world"

                      echo <+trigger.payload.repository.name>
                      echo "====="
                      echo "Pipeline variables"
                      echo <+pipeline.variables.reponame>
                      echo "====="

                      echo <+<+pipeline.variables.reponame>.replaceAll('-|\\.','specialchars')>
                      echo <+<+pipeline.variables.reponame>.contains("dummy")>
                      echo "====="

                      echo <+trigger.payload>
                      echo "====="
                      echo <+trigger>
  variables:
    - name: reponame
      type: String
      description: ""
      required: false
      value: <+trigger.payload.repository.name>
    - name: inputvariable
      type: String
      description: ""
      required: false
      value: <+input>
    - name: inputvariable2
      type: String
      description: ""
      required: false
      value: <+input>
  identifier: triggertest_Clone
  name: trigger-test - Clone
